# Generated by Django 5.2.12 on 2026-03-27 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasseioGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_id', models.CharField(max_length=100, unique=True)),
                ('titulo_pt', models.CharField(max_length=255)),
                ('titulo_en', models.CharField(max_length=255)),
                ('titulo_es', models.CharField(max_length=255)),
                ('titulo_fr', models.CharField(max_length=255)),
                ('descricao_pt', models.TextField()),
                ('descricao_en', models.TextField()),
                ('descricao_es', models.TextField()),
                ('descricao_fr', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasseioCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_id', models.CharField(max_length=100)),
                ('oculto', models.BooleanField(default=False)),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='passeios/')),
                ('exclusivo', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'tour_id')},
            },
        ),
    ]
