# Generated by Django 5.2.7 on 2026-04-10 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda', models.CharField(max_length=10)),
                ('cotacao_oficial', models.DecimalField(decimal_places=4, max_digits=10)),
                ('percentual_lucro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cotacao_venda', models.DecimalField(decimal_places=4, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('foto_capa', models.ImageField(blank=True, null=True, upload_to='hoteis/capas/')),
                ('titulo_hero', models.CharField(default='Experiências Exclusivas', max_length=255)),
                ('subtitulo_hero', models.CharField(default='Selecione seu próximo destino', max_length=255)),
                ('titulo_hero_en', models.CharField(blank=True, max_length=255)),
                ('subtitulo_hero_en', models.CharField(blank=True, max_length=255)),
                ('titulo_hero_es', models.CharField(blank=True, max_length=255)),
                ('subtitulo_hero_es', models.CharField(blank=True, max_length=255)),
                ('titulo_hero_fr', models.CharField(blank=True, max_length=255)),
                ('subtitulo_hero_fr', models.CharField(blank=True, max_length=255)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('subtitulo', models.CharField(blank=True, max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heroes', to='core.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='CambioTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda', models.CharField(max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cotacao_usada', models.DecimalField(decimal_places=4, max_digits=10)),
                ('valor_reais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lucro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambio_transacoes', to='core.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Passeio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_sob_consulta', models.BooleanField(default=False)),
                ('preco_por_pessoa', models.BooleanField(default=False)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('subtitulo', models.CharField(blank=True, max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='passeios/banner/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('nome_en', models.CharField(blank=True, max_length=255)),
                ('descricao_en', models.TextField(blank=True)),
                ('nome_es', models.CharField(blank=True, max_length=255)),
                ('descricao_es', models.TextField(blank=True)),
                ('nome_fr', models.CharField(blank=True, max_length=255)),
                ('descricao_fr', models.TextField(blank=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passeios', to='core.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ImagemPasseio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='passeios/galeria/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('passeio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.passeio')),
            ],
        ),
        migrations.CreateModel(
            name='PasseioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('vagas', models.IntegerField(default=0)),
                ('passeio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='core.passeio')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hotel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('qtd_pessoas', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('data_reserva', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.hotel')),
                ('passeio_agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.passeioagenda')),
            ],
        ),
    ]
