# Generated by Django 5.2.12 on 2026-04-07 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='passeiocustom',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passeios_customizados', to='core.hotel'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hotel'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ImagemPasseio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='passeios/galeria/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('passeio_custom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.passeiocustom')),
            ],
        ),
    ]
