# Generated by Django 5.2.7 on 2026-04-11 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_reserva_qtd_pessoas_reserva_data_passeio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='valor_total',
            new_name='comissao_agencia',
        ),
        migrations.AddField(
            model_name='reserva',
            name='comissao_recepcao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('pendente', 'Pendente')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='recepcionista',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reserva',
            name='valor_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmada', 'Confirmada'), ('realizado', 'Passeio Realizado'), ('pago', 'Pago'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='ConfiguracaoDivisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_hotel', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('nomes_recepcionistas', models.TextField(blank=True, default='')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='divisao', to='core.hotel')),
            ],
        ),
    ]
