# Generated by Django 5.2.12 on 2026-04-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_passeiocustom_hotel_alter_perfil_hotel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passeio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passeios', to='core.hotel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='passeiocustom',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='passeiocustom',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='imagempasseio',
            name='passeio_custom',
        ),
        migrations.DeleteModel(
            name='PasseioGlobal',
        ),
        migrations.AddField(
            model_name='imagempasseio',
            name='passeio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.passeio'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PasseioCustom',
        ),
    ]
