# Generated by Django 5.2.7 on 2026-04-11 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_valor_total_reserva_comissao_agencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mes_referencia',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pix_recebimentos',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Adiantamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recepcionista', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(blank=True, null=True)),
                ('mes_referencia', models.CharField(blank=True, default='', max_length=7)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adiantamentos', to='core.hotel')),
            ],
        ),
    ]
