# Generated by Django 5.2.12 on 2026-04-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passeio_alter_passeiocustom_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passeio',
            name='descricao_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='passeio',
            name='descricao_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='passeio',
            name='descricao_fr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='passeio',
            name='nome_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='passeio',
            name='nome_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='passeio',
            name='nome_fr',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
