# Generated by Django 5.2.7 on 2026-04-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reserva_data_pagamento_reserva_mes_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambiotransacao',
            name='cotacao_compra',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cambiotransacao',
            name='cotacao_venda',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cambiotransacao',
            name='valor_recebido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
