# Generated by Django 5.2.12 on 2026-04-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_passeio_descricao_en_passeio_descricao_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='foto_capa',
            field=models.ImageField(blank=True, null=True, upload_to='hoteis/capas/'),
        ),
    ]
