# Generated by Django 5.2.13 on 2026-04-15 17:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cambiotransacao_cotacao_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='foto_capa',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='imagempasseio',
            name='arquivo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
