# Generated by Django 5.2.13 on 2026-04-17 14:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_hero_banner_alter_hotel_foto_capa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passeio',
            name='banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
