# Generated by Django 5.2.13 on 2026-04-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_configuracaodivisao_pcts_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='mapa_embed',
            field=models.TextField(blank=True),
        ),
    ]
