# Generated by Django 5.2.13 on 2026-04-27 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_hotel_mapa_embed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['cargo', 'user__username']},
        ),
        migrations.AddField(
            model_name='perfil',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('recepcionista', 'Recepcionista')], default='recepcionista', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='criado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='perfil',
            name='permissoes_json',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfis', to='core.hotel'),
        ),
    ]
